In [1]:
from itertools import product
import numpy as np

In [18]:
def v (n, q):
    """construct a linear space of dimension n over a finite field of order q"""
    return [''.join(str(pos) for pos in comb) for comb in list(product(range(q), repeat=n))]

---

__Exercise 7.6__
Let $C$ be the ternary linear code with generator matrix
$$
\begin{bmatrix}
1 & 1 & 1 & 0\\
2 & 0 & 1 & 1
\end{bmatrix}
\text{.}
$$
(a) Find a generator matrix for $C$ in standard form.<br>
(b) Find a parity-check matrix for $C$ in standard form.<br>
(c) Use syndrome decoding to decode the received vectors $2121$, $1201$, and $2222$.

---

Theorem 5.5 (Standard-Form Generator Matrix Procedure)

$$
\begin{bmatrix}
1 & 1 & 1 & 0\\
2 & 0 & 1 & 1
\end{bmatrix}
\rightarrow
\begin{bmatrix}
1 & 1 & 1 & 0\\
0 & 1 & 2 & 1
\end{bmatrix}
\rightarrow
\begin{bmatrix}
1 & 0 & 2 & 2\\
0 & 1 & 2 & 1
\end{bmatrix}
$$

$\mathbf{u}G = \mathbf{x}$

$$
\begin{bmatrix}
0 & 0\\
0 & 1\\
0 & 2\\
1 & 0\\
1 & 1\\
1 & 2\\
2 & 0\\
2 & 1\\
2 & 2\\
\end{bmatrix}
\begin{bmatrix}
1 & 0 & 2 & 2\\
0 & 1 & 2 & 1
\end{bmatrix}
=
\begin{bmatrix}
0 & 0 & 0 & 0\\
0 & 1 & 2 & 1\\
0 & 2 & 1 & 2\\
1 & 1 & 1 & 0\\
1 & 2 & 0 & 1\\
2 & 0 & 1 & 1\\
2 & 1 & 0 & 2\\
2 & 2 & 2 & 0\\
\end{bmatrix}
$$

Theorem 7.6 (Standard-Form Parity-Check Matrix from Standard-Form Generator Matrix)

\begin{bmatrix}
1 & 1 & 1 & 0\\
1 & 2 & 0 & 1
\end{bmatrix}

$C$ is a linear $[4, 2]$-code with $d(C)=3$ by Theorem 5.2.<br>
Since $t=1$, all nine vectors of weight $\leq 1$ are coset leaders with the weight-zero vector serving as the coset leader of $C$.<br>
The number of cosets (and coset leaders) is
$$\frac{q^n}{q^k}=\frac{3^4}{3^2}=3^2=9$$
which are just the nine vectors of weight $\leq 1$.<br>
In other words, $C$ is a perfect code (which is also shown by obtaining equality in the sphere-packing bound).<br>
By the sphere-packing bound for a binary $(4,9,3)$-code
$$
3^2\left\{\binom{4}{0}+\binom{4}{1}(3-1)\right\}\leq 3^4
$$
$$
\Rightarrow 9\left\{1+8\right\}\leq 81
$$
$$
\Rightarrow 81 = 81
$$

Compute the syndromes $S(\mathbf{y})=H\mathbf{y}$ of the nine coset leaders in order to construct a syndrome lookup table.
$$
\begin{bmatrix}
0 & 1 & 2 & 1 & 2 & 1 & 2 & 0 & 0\\
0 & 1 & 2 & 2 & 1 & 0 & 0 & 1 & 2\\
\end{bmatrix}
=
\begin{bmatrix}
1 & 1 & 1 & 0\\
1 & 2 & 0 & 1\\
\end{bmatrix}
\begin{bmatrix}
0 & 1 & 2 & 0 & 0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 1 & 2 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 1 & 2 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 2\\
\end{bmatrix}
$$
Decoding Procedure
1. To decode a received vector $\mathbf{y}$, compute its syndrome $S(\mathbf{y})$
2. Let $\mathbf{z}=S(\mathbf{y})$ and locate $\mathbf{z}$ in the first column of the lookup table
3. Decode $\mathbf{y}$ as $\mathbf{y}-f(\mathbf{z})$ where $f(\mathbf{z})$ is the coset leader that matches with $\mathbf{z}$

$S(\mathbf{y})=H\mathbf{y}\Rightarrow\mathbf{y}-\mathbf{e}=\mathbf{x}$<br>
$S(2121)=22\Rightarrow 2121-2000=0121$<br>
$S(1201)=00\Rightarrow 1201-0000=1201$<br>
$S(2222)=02\Rightarrow 2222-0002=2220$

In [21]:
n = 2
q = 3
messages = np.array([list(i) for i in v(n, q)], dtype=int)
generator = np.array([['1', '0', '2', '2'], ['0', '1', '2', '1']], dtype=int)
code = np.mod(np.dot(messages, generator), q)

print('Messages')
print(messages)
print()
print('Standard-Form Generator')
print(generator)
print()
print('Code')
print(code)

Messages
[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]
 [2 0]
 [2 1]
 [2 2]]

Standard-Form Generator
[[1 0 2 2]
 [0 1 2 1]]

Code
[[0 0 0 0]
 [0 1 2 1]
 [0 2 1 2]
 [1 0 2 2]
 [1 1 1 0]
 [1 2 0 1]
 [2 0 1 1]
 [2 1 0 2]
 [2 2 2 0]]


---

__Example 7.12__
The set of all 10-digit telephone numbers in the UK is a denary $(10, M, d)$-code. It's possible to use a code over 82 million 10-digit telephone numbers such that if just one digit of any number is misdialled the correct connection can nevertheless be made.<br>
Let there be an undenary $[10,8]$-code with nonstandard-form parity-check matrix $H=$
$$
\begin{bmatrix}
1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
\end{bmatrix}
$$
Let $C$ be a denary $(10, M, d)$-code obtained from this undenary code by omitting all those codewords which contain the digit '$10$'.

$(10, M, d)$-code $\subset[10,8]$-code $\subset V(10,11)$<br>
$\vert V(10,11)\vert=11^{10}=25937424601\approx26$ billion<br>
$\vert [10,8]$-code$\vert=11^8=214358881\approx200$ million<br>
$\vert(10, M, d)$-code$\vert=82644629$

__Exercise 7.7__
Using the code of Example 7.12, decode the received vector $0617960587$.

---

__Exercise 7.10__
Suppose a certain binary channel accepts words of length 7 and that the only kind of error vector ever observed is one of the eight vectors $0000000$, $0000001$, $0000011$, $0000111$, $0001111$, $0011111$, $0111111$, $1111111$. Design a binary linear $[7, k]$-code which will correct all such errors with as large a rate as possible.

---